apiVersion: apps/v1
kind: Deployment
metadata:
 name: python-distroless
 labels:
   app: python-distroless
   tier: frontend
   version: v1
spec:
 selector:
   matchLabels:
     app: python-distroless
     tier: frontend
     version: v1
 replicas: 1
 template:
   metadata:
     labels:
       app: python-distroless
       tier: frontend
       version: v1
   spec:
     terminationGracePeriodSeconds: 100
     containers:
     - name: python-distroless
       image: "python-distroless:latest"
       imagePullPolicy: Never
       resources:
         limits:
           cpu: "1000m"
           memory: 1500Mi
         requests:
           cpu: 500m
           memory: 700Mi