apiVersion: v1
kind: Service
metadata:
 name: python-distroless-svc
 namespace: default
 labels:
   app: python-distroless
   tier: frontend
   version: v1
spec:
 type: NodePort
 ports:
 - port: 5000
 selector:
    app: python-distroless
    tier: frontend
    version: v1